import Head from 'next/head';
import { AuthScreen } from '../screens/auth';
import { GroupScreen } from '../screens/Group';
import { CreateScreen } from '../screens/Create';

import { DashboardScreen } from '../screens/dashboard';
import { useAuthContext } from '../contexts/AuthContext';
import dynamic from 'next/dynamic';

export default function Home() {
  const { address, ethProvider } = useAuthContext();
  return (
    <div>
      <Head>
        <title>Gullak Wallet</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main>{address != null ? <DashboardScreen /> : <CreateScreen />}</main>
    </div>
  );
}
