import Head from 'next/head';
import { useState } from 'react';
import { Etherspot, TRANSACTION_BLOCK_TYPE } from '@etherspot/react-transaction-buidler';
import { AuthScreen } from '../screens/auth';
import { DashboardScreen } from '../screens/dashboard';
import { ethers } from 'ethers';

export default function Home() {
  const [connectedProvider, setConnectedProvider] = useState<ethers.providers.Web3Provider | null>(null);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main>{connectedProvider != null ? <DashboardScreen /> : <AuthScreen setConnectedProvider={setConnectedProvider} />}</main>
    </div>
  );
}
